/* Generated By:JavaCC: Do not edit this line. FTAParserConstants.java */
package dfta.parser;

public interface FTAParserConstants {

  int EOF = 0;
  int FINAL = 5;
  int STATES = 6;
  int TRANSITIONS = 7;
  int LBRACE = 8;
  int RBRACE = 9;
  int LSQBRACE = 10;
  int RSQBRACE = 11;
  int VERTBAR = 12;
  int UNDERSCORE = 13;
  int COMMA = 14;
  int FULLSTOP = 15;
  int ARROW = 16;
  int QUOTE = 17;
  int BINOP = 18;
  int ANYOP = 19;
  int NUMBER = 20;
  int DECIMALNUMBER = 21;
  int IDENTIFIER = 22;
  int LETTER = 23;
  int DIGIT = 24;
  int QIDENT = 25;
  int NONQUOTE = 26;
  int SINGLE_LINE_COMMENT = 27;
  int MULTI_LINE_COMMENT = 28;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Final\"",
    "\"States\"",
    "\"Transitions\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\"_\"",
    "\",\"",
    "\".\"",
    "\"->\"",
    "\"\\\'\"",
    "<BINOP>",
    "<ANYOP>",
    "<NUMBER>",
    "<DECIMALNUMBER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<QIDENT>",
    "<NONQUOTE>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
  };

}
