//
// Generated by JTB 1.3.2
//

package dfta.parser.visitor;
import dfta.parser.syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( FinalStates() )?
    * f1 -> ( <TRANSITIONS> <FULLSTOP> )?
    * f2 -> Delta()
    * f3 -> <EOF>
    */
   public R visit(FTA n, A argu);

   /**
    * f0 -> <FINAL>
    * f1 -> <STATES>
    * f2 -> Ident()
    * f3 -> ( Ident() )*
    * f4 -> <FULLSTOP>
    */
   public R visit(FinalStates n, A argu);

   /**
    * f0 -> ( Transition() )*
    */
   public R visit(Delta n, A argu);

   /**
    * f0 -> LHS()
    * f1 -> RHS()
    * f2 -> <FULLSTOP>
    */
   public R visit(Transition n, A argu);

   /**
    * f0 -> Ident() ( <LBRACE> Ident() ( <COMMA> Ident() )* <RBRACE> <ARROW> | <ARROW> | <BINOP> Ident() <ARROW> | <ANYOP> Ident() <ARROW> | <COMMA> Ident() <ARROW> )
    *       | <NUMBER> <ARROW>
    *       | <ANYOP> ( <NUMBER> | Ident() ) <ARROW>
    *       | <LSQBRACE> ( Ident() <VERTBAR> Ident() <RSQBRACE> <ARROW> | <RSQBRACE> <ARROW> )
    *       | <LBRACE> Ident() ( <COMMA> | <BINOP> ) Ident() <RBRACE> <ARROW>
    */
   public R visit(LHS n, A argu);

   /**
    * f0 -> Ident()
    */
   public R visit(RHS n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    *       | <QIDENT>
    */
   public R visit(Ident n, A argu);

}
