//
// Generated by JTB 1.3.2
//

package dfta.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> <AUTOMATON>
 * f1 -> <IDENTIFIER>
 */
public class Automaton implements Node {
   public NodeToken f0;
   public NodeToken f1;

   public Automaton(NodeToken n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public Automaton(NodeToken n0) {
      f0 = new NodeToken("Automaton");
      f1 = n0;
   }

   public void accept(dfta.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(dfta.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(dfta.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(dfta.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

