//
// Generated by JTB 1.3.2
//

package dfta.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> <OPS>
 * f1 -> LabelList()
 */
public class OpsDecls implements Node {
   public NodeToken f0;
   public LabelList f1;

   public OpsDecls(NodeToken n0, LabelList n1) {
      f0 = n0;
      f1 = n1;
   }

   public OpsDecls(LabelList n0) {
      f0 = new NodeToken("Ops");
      f1 = n0;
   }

   public void accept(dfta.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(dfta.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(dfta.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(dfta.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

