//
// Generated by JTB 1.3.2
//

package dfta.parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> OpsDecls()
 * f1 -> Automaton()
 * f2 -> States()
 * f3 -> FinalStates()
 * f4 -> TimbukTransitions()
 * f5 -> <EOF>
 */
public class TimbukFTA implements Node {
   public OpsDecls f0;
   public Automaton f1;
   public States f2;
   public FinalStates f3;
   public TimbukTransitions f4;
   public NodeToken f5;

   public TimbukFTA(OpsDecls n0, Automaton n1, States n2, FinalStates n3, TimbukTransitions n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public TimbukFTA(OpsDecls n0, Automaton n1, States n2, FinalStates n3, TimbukTransitions n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = new NodeToken("");
   }

   public void accept(dfta.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(dfta.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(dfta.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(dfta.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

